/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_DisasterModeNative */



extern "C" {

/*
 * Class:     com_android_settings_DisasterModeNative
 * Method:    updateColorScheme
 * Signature: (I)I
 */

jint updateColorScheme(JNIEnv *, jobject, jint);

/*
 * Class:     com_android_settings_DisasterModeNative
 * Method:    updateVSync
 * Signature: (I)I
 */

jint updateVSync(JNIEnv *, jobject, jint);



/*
 * Class:     com_android_settings_DisasterModeNative
 * Method:    updateDMProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
jint updateDMProperty(JNIEnv *, jclass, jstring, jstring);


}


